### ISSUE TITLE
Upgraded the benchmark with newer language version: PointByIn is in par with PointByRef

### ISSUE THREAD

**Issue by ceztko** [bgrainger/InPerformance#2]
I noticed that running your benchmark selecting new language version fixes the expectation that `PointByIn` should be in par with `PointByRef`. These are the results with `LangVersion` set to 10 (the default in .NET6.0):

```
|               Method |       Mean |     Error |    StdDev |
|--------------------- |-----------:|----------:|----------:|
|         PointByValue | 15.9881 ns | 0.1009 ns | 0.0943 ns |
|           PointByRef |  0.0399 ns | 0.0069 ns | 0.0064 ns |
|            PointByIn |  0.0467 ns | 0.0072 ns | 0.0064 ns |
| ReadOnlyPointByValue | 15.8105 ns | 0.0857 ns | 0.0716 ns |
|   ReadOnlyPointByRef |  0.0000 ns | 0.0000 ns | 0.0000 ns |
|    ReadOnlyPointByIn |  0.0442 ns | 0.0061 ns | 0.0057 ns |
```
**EDIT**: I repeated the benchmark because ReadOnlyPointByValue was reported too slow in previous run. Possibly some jitter when running if the first time.

This makes more sense to me. The following are with `LangVersion` set to 7.2:

```
|               Method |       Mean |     Error |    StdDev |
|--------------------- |-----------:|----------:|----------:|
|         PointByValue | 16.0793 ns | 0.0561 ns | 0.0469 ns |
|           PointByRef |  0.0000 ns | 0.0000 ns | 0.0000 ns |
|            PointByIn | 16.6271 ns | 0.0373 ns | 0.0312 ns |
| ReadOnlyPointByValue | 15.7036 ns | 0.0506 ns | 0.0423 ns |
|   ReadOnlyPointByRef |  0.0365 ns | 0.0096 ns | 0.0085 ns |
|    ReadOnlyPointByIn |  0.0470 ns | 0.0051 ns | 0.0048 ns |
```

They possibly introduced the optimization later in the language version, or it's a compiler bug. I attached the used project files:
[InPerformance-NET6CSharp10.csproj.txt](https://github.com/bgrainger/InPerformance/files/11465693/InPerformance-NET6CSharp10.csproj.txt)
[InPerformance-NET6CSharp72.csproj.txt](https://github.com/bgrainger/InPerformance/files/11465696/InPerformance-NET6CSharp72.csproj.txt)

**Comment by ceztko** [comment]
Another interesting fact: The optimization is enabled since at least `LangVersion` 8.0. In 7.3 the optimization is still disabled.

**Comment by bgrainger** [comment]
Thanks for the feedback.

.NET and C# have added many more optimisations and features since I created this repository. It's really of historical interest only; I'm going to archive it.
